<a href="https://colab.research.google.com/github/theAkhileshRai/DeepLearning/blob/master/dashboards/Plotly/LineChart02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Plotly Basics

In [0]:
! pip install plotly

Requirement already satisfied: plotly in /usr/local/lib/python3.6/dist-packages (4.4.1)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from plotly) (1.12.0)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.6/dist-packages (from plotly) (1.3.3)

In [0]:
import numpy as np
import pandas as pd
import plotly.offline as pyo
import plotly.graph_objs as go

In [0]:
df = pd.read_csv('/content/nst-est2017-alldata.csv')

In [0]:
df2 = df[df['DIVISION']=='1']
df2.set_index('NAME',inplace=True)

In [17]:
df2.head()

               SUMLEV REGION DIVISION  ...  RNETMIG2015  RNETMIG2016  RNETMIG2017
NAME                                   ...
Connecticut      40.0      1        1  ...    -3.464252    -3.112421    -1.257548
Maine            40.0      1        1  ...     0.389959     3.000731     5.216532
Massachusetts    40.0      1        1  ...     3.276287     2.261905     3.246090
New Hampshire    40.0      1        1  ...     0.852258     3.037729     5.170643
Rhode Island     40.0      1        1  ...     0.368598     0.526146     0.891742

[5 rows x 120 columns]

In [0]:
list_of_pop_col = [col for col in df2.columns if col.startswith('POP')]

In [19]:
list_of_pop_col

['POPESTIMATE2010',
 'POPESTIMATE2011',
 'POPESTIMATE2012',
 'POPESTIMATE2013',
 'POPESTIMATE2014',
 'POPESTIMATE2015',
 'POPESTIMATE2016',
 'POPESTIMATE2017']

In [0]:
df2 = df2[list_of_pop_col]

In [22]:
df2

               POPESTIMATE2010  ...  POPESTIMATE2017
NAME                            ...
Connecticut          3580171.0  ...        3588184.0
Maine                1327568.0  ...        1335907.0
Massachusetts        6564943.0  ...        6859819.0
New Hampshire        1316700.0  ...        1342795.0
Rhode Island         1053169.0  ...        1059639.0
Vermont               625842.0  ...         623657.0

[6 rows x 8 columns]

In [26]:
df2.loc['Connecticut']

POPESTIMATE2010    3580171.0
POPESTIMATE2011    3591927.0
POPESTIMATE2012    3597705.0
POPESTIMATE2013    3602470.0
POPESTIMATE2014    3600188.0
POPESTIMATE2015    3593862.0
POPESTIMATE2016    3587685.0
POPESTIMATE2017    3588184.0
Name: Connecticut, dtype: float64

In [0]:
data = [go.Scatter(x=df2.columns,y=df2.loc[name],mode= 'lines' ,name= name ) for name in df2.index]

In [28]:
pyo.plot(data)

'temp-plot.html'